### ISSUE TITLE
Document commons tasks

### ISSUE THREAD

**Issue by mikaelkindborg** [evothings/evothings-doc#74]
Tasks that are common but not obvious needs to be documented and presented to the user in some way.

One example is this user feedback:

"I pressed the 'x' in the upper right of a SensorTag example app in
the client (the main window, not the coding one), and it disappeared.
How do I get it to come back?"

We could document the UI for drag & drop much better, with pictures,
and also perhaps include a shortcut from the drop-down menu. Perhaps
we should have some kind of FAQ for common tasks and problems?

Alex had an idea about making an "Empty Project" with instructions for
how to create an app from  one of the examples, those instructions
could also explain the drag & drop UI.

**Comment by psvensson** [comment]
This issue is about workbench documentation
