### ISSUE TITLE
Cordova Guide: remove meta tag

### ISSUE THREAD

**Issue by fredrikeldh** [evothings/evothings-doc#81]
Some recent versions of Cordova (which ones?) create a default index.html file containing a tag ```meta http-equiv="Content-Security-Policy"```, which interferes with our workbench. Update the guide to advise users to remove that tag from newly created projects.

Source: https://evothings.com/forum/viewtopic.php?f=8&t=1525

**Comment by divineprog** [comment]
Info added by this pull request: https://github.com/evothings/evothings-doc/pull/82
