### ISSUE TITLE
Document how to use BLE (BLE Guide)

### ISSUE THREAD

**Issue by mikaelkindborg** [evothings/evothings-doc#96]
Write "generic" BLE guide, which explains how to implemet support for any BLE-device using JavaScript libraries.

Here is a question about how to access values in the data received from a BLE device, see this post:

http://stackoverflow.com/questions/30827376/using-evothings-javascript-to-read-ble-characteristic-data/34334876#34334876

**Comment by gokr** [comment]
Summer work :) Thus postponed to Sprint Jolene.

**Comment by mikaelkindborg** [comment]
Also see this issue: https://github.com/evothings/cordova-ble/issues/15

**Comment by mikaelkindborg** [comment]
BLE Guide published here: https://evothings.com/doc/tutorials/how-to-connect-to-ble-devices.html
